POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "",
    "number": "0893838927"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Oleg Kostadinov",
    "number": ""
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "",
    "number": ""
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "0893838927"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Oleg Kostadinov",
    "number": "0893838927"
}